### PR TITLE
Tooltips Feature

### PR DESCRIPTION
**Pull request by quarties**
Simple CSS based tooltips feature implemented in 'Reading now' and 'Show people online' to show email in 'data-tooltip' instead of 'title' attribute. Usage explained in new page template.

New page template: http://take.ms/KzLjE
Reading now: http://take.ms/mo6qv
Show people online: http://take.ms/PGd27

### CODE REVIEW

**Comment by bolchowka** [comment]
Thanks for the pull request. There are a number of things that must be fixed before I can merge it to master.

1. `npm start` displays a warning:
```
./src/components/person/Person.js
  Line 6:  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
```
Please fix this warning, possibly by not using `<a>` tags to display a tooltip. Do not use `<a>` tags if you do not link to other pages.

2. Tooltips work differently for the same text:
screen shot 2017-09-22 at 10 04 29
screen shot 2017-09-22 at 10 04 39

3. Please do not use vendor prefixes in the CSS code (see: `/src/css/tooltips.css`).

**Comment by quarties** [comment]
@bolchowka thanks for checking, sorry for the issues

1. `npm start` is now free of any warnings, it was a good point - I moved `<a>` elements to `<span>`

2. The issue here was `word-wrap: break-word` inherited from `content--markdown` css class. I added it to all tooltips (because it's a good idea to break words there) + added a new clas `tooltip-auto` which contains `width: auto` for long words (like emails)

3. removed all vendor prefixes

**Comment by quarties** [comment]
@bolchowka all issues had been fixed - can you review the request again?

**Comment by quarties** [comment]
@bolchowka all issues had been fixed - can you review the request again?

**Comment by bolchowka** [comment]
@quarties just merged to master. Thanks for contribution!

**Pull request merged**
